monitor=,preferred,auto,1

exec-once = quickshell --path /etc/quickshell/login.qml

animations {
	enabled = false
}

misc {
	disable_hyprland_logo = true
	disable_splash_rendering = true
}

input {
	kb_layout = us
}

input {
	follow_mouse = true
}

cursor {
	no_hardware_cursors = true
}

debug {
	disable_logs = false
}